# following line is key to prevent an endless build/deploy cycle
# when travis commits to pages:
if: commit_message !~ ^Deploy.*
dist: xenial
env:
  global:
  - PERL5LIB=/usr/share/perl5
language: python
services:
  - docker
python:
  - '3.8'
branches:
  only:
    - master
before_install:
  - docker pull maj1/icdc:model-tool-perl
  # - sudo apt update && sudo apt install -y cpanminus

install:
  - git clone https://github.com/CBIIT/bento-mdf
  - cp -aR bento-mdf/drivers/Perl/make-model/lib lib
  - cp -aR bento-mdf/drivers/Perl/make-model/bin bin  
  - pip install bento-mdf/validators/mdf-validate
  - pip install -r python/requirements-dev.txt
  - pip install -r python/requirements.txt
  - pip install sphinx
  - pip install sphinx-rtd-theme
  
# Tasks:
# - check validity of metamodel.yaml
# - create metamodel.svg from metamodel.yaml
# - test perl driver
# - test python driver
# - build python docs
# - build python package and push

script:
  # - check validity of metamodel.yaml
  - test-mdf.py metamodel.yaml
  # - create metamodel.svg from metamodel.yaml  
  - docker run --rm -it -v "$PWD":/home/user -w /home/user maj1/icdc:model-tool-perl -Ilib bin/model-tool -g metamodel.svg metamodel.yaml
  # - test perl driver
  # - pushd perl
  # - perl Build.PL
  # - ./Build installdeps --cpan_client cpanm
  # - ./Build test
  # - popd
  # - test python driver
  - pushd python
  - tox
  # - build package
  - python setup.py sdist
  - popd
  # - build python docs
  - pushd python/docs
  - ./build-docs.sh
  - popd
  # - cleanup
  - rm -rf bento-mdf
  - rm -rf bin
  - rm -rf lib

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep_history: true
  verbose: true
  on:
    branch: master

