---
abstract: 'Tools for manipulating a Bento Metamodel Database'
author:
  - 'Mark A. Jensen'
build_requires:
  IO::Pty: '0'
  IPC::Run: '0'
  Test::Exception: '0'
  Test::Warn: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4229, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bento-Meta
provides:
  Bento::Meta:
    file: lib/Bento/Meta.pm
    version: '0.21'
  Bento::Meta::MDF:
    file: lib/Bento/Meta/MDF.pm
  Bento::Meta::Model:
    file: lib/Bento/Meta/Model.pm
  Bento::Meta::Model::Concept:
    file: lib/Bento/Meta/Model/Concept.pm
  Bento::Meta::Model::Edge:
    file: lib/Bento/Meta/Model/Edge.pm
  Bento::Meta::Model::Entity:
    file: lib/Bento/Meta/Model/Entity.pm
  Bento::Meta::Model::Node:
    file: lib/Bento/Meta/Model/Node.pm
  Bento::Meta::Model::ObjectMap:
    file: lib/Bento/Meta/Model/ObjectMap.pm
  Bento::Meta::Model::Origin:
    file: lib/Bento/Meta/Model/Origin.pm
  Bento::Meta::Model::Property:
    file: lib/Bento/Meta/Model/Property.pm
  Bento::Meta::Model::Term:
    file: lib/Bento/Meta/Model/Term.pm
  Bento::Meta::Model::ValueSet:
    file: lib/Bento/Meta/Model/ValueSet.pm
requires:
  Hash::Merge: '0.300'
  JSON::ize: '0.202'
  Log::Log4perl: '0'
  Neo4j::Bolt: '0.12'
  Neo4j::Cypher::Abstract: '0.1003'
  Scalar::Util: '0'
  Try::Tiny: '0'
  UUID::Tiny: '0'
  YAML::PP: '0.018'
version: '0.21'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
