name: ci-cd

on: [push, pull_request]

jobs:
    ci-cd:
      uses: CBIIT/bento-workflows/.github/workflows/ci-cd.yml@c1fc92ea00e7a8960b4dfd9306eb3e985821d37f
      with:
        workdir: ./python
        versions: |
          ["3.10","3.11","3.12","3.13"]
        pkg_name: bento-meta
      secrets: inherit
