name: ci-cd

on: [push, pull_request]

jobs:
    ci-cd:
      uses: CBIIT/bento-workflows/.github/workflows/ci-cd.yml@v2.1.7
      with:
        workdir: ./python
        pkg_name: bento-meta
        python_versions:
          - 3.8
          - 3.9
          - 3.10
          - 3.11