name: ci-cd

on: [push, pull_request]

jobs:
    ci-cd:
      uses: CBIIT/bento-workflows/.github/workflows/ci-cd.yml@v2.3.11
      with:
        workdir: ./python
        versions: |
          ["3.10","3.11","3.12","3.13"]
        pkg_name: bento-meta
      secrets: inherit
