name: ci-cd

on: [push, pull_request]

jobs:
    ci-cd:
      uses: CBIIT/bento-workflows/.github/workflows/ci-cd.yml@ef9c1e2a1e77055da3855955882cc4cabf1f3e32
      with:
        workdir: ./python
        versions: |
          ["3.10","3.11","3.12","3.13"]
        pkg_name: bento-meta
      secrets: inherit
