name: ci-cd

on: [push, pull_request]

jobs:
    ci-cd:
      uses: CBIIT/bento-workflows/.github/workflows/ci-cd.yml@v2.2.10
      with:
        workdir: ./python
        pkg_name: bento-meta
      secrets: inherit