name: ci-cd

on: [pull_request]

jobs:
    ci-cd:
      uses: CBIIT/bento-workflows/.github/workflows/ci-cd.yml@v2.3.1
      with:
        workdir: ./python
        pkg_name: bento-meta
      secrets: inherit
