name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
      - name: Update lock
        working-directory: ./python
        run: |
          poetry lock
      - name: Install package
        working-directory: ./python
        run: |
          poetry install --all-extras
      - name: Sphinx build
        working-directory: ./python/docs
        run: |
          poetry run python -m ipykernel install --user --name "ipykernel"
          poetry run sphinx-build -b html . ./_build/html
      - name: List HTML Output
        run: ls -R ./python/docs/_build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./python/docs/_build/html
          force_orphan: true
